claim/test_validations.py
claim/validations.py

Additional tests and fixes for limits and things that apparently were not included in the previous PR.
The tests will only pass if the openimis-be-product_py project is updated from develop as the test product limitations had to be adapted. This should fix OMT-165 and OMT-170

More validation fixes

---

claim/gql_mutations.py
claim/test_helpers.py
claim/test_validations.py
claim/validations.py

Missing parts with the dedrem fixes cherry picked from master

Omt 204 components upgrade

---

claim/gql_mutations.py
claim/models.py

The previous 4 PRs were between incorrect branches and they are all linked to each other, so merging them in this PR.

Hotfix merge of OMT-235 OMT-236 and OMT-237

---

claim/schema.py

PR is due to working on [OAI-23](https://openimis.atlassian.net/browse/OAI-23). For filtering by was_categorized is required. 
This change depends on [lookup added to core module.](https://github.com/openimis/openimis-be-core_py/pull/30)

OAI-23: Added fitlering by json_ext to claim graphql

---

claim/gql_queries.py

TICKET: [OAI-36](https://openimis.atlassian.net/browse/OAI-36)

OAI-36: Remove duplicates from claim gql query 

---

claim/gql_queries.py

TICKET: [OAI-45](https://openimis.atlassian.net/browse/OAI-45)

OAI-45: Remove duplicated records in claim query

---

claim/gql_mutations.py
claim/schema.py

TICKET: [OAI-49](https://openimis.atlassian.net/browse/OAI-49)

OAI-49: Added filter_validity to schema

---

claim/services.py
claim/test_services.py

PR is part of [OE0-106](https://openimis.atlassian.net/browse/OE0-106) bug fixing. 
Validation prevents entering new claim with already existing code.

OE0-106: Claim code validation added to ClaimCreateService

---

claim/gql_mutations.py
claim/gql_queries.py
claim/utils.py

- claim service and item were not deleted, fixed in develop

fix item/s and service/s not deleted in claim detail

---

claim/test_services.py
claim/test_validations.py
claim/validations.py

[https://openimis.atlassian.net/browse/OP-868](https://openimis.atlassian.net/browse/OP-868)
Changes:
- Changed handling of JSON fields from JSON strings to python dictionaties (Django 3.2 update)
- Fixed TestCase handling (added all missing calls to super.setUpClass, super.setUp, removed unecessary teardowns)
- Removed some unused code/comments/imports
- Fixed code formatting

OP-868 Fix CI issues caused by Django 3.2 update

---

claim/gql_mutations.py
claim/models.py

Ticket: https://openimis.atlassian.net/browse/OP-404
Changes:
- Feedback Prompt model added
- Feedback Prompts generated when claim is "selected"
- Feedback Prompts validityTo set to null when claim is "not selected" or "bypassed" and after review.

OP-404: Feedback Prompts support added.

---

claim/schema.py

Ticket:
https://openimis.atlassian.net/browse/OP-1041
Changes:
- added query set filtering when it is not filtered on the front
- few related code lines validated with PEP8
Related PR:
https://github.com/openimis/openimis-fe-claim_js/pull/70

Feature/op 1041: added filter for Claim Admins based on Health Facility

---

claim/management/commands/generateclaims.py

Items where actually picked from services
Price and quantities have been made random

generateclaims use random item, not service

---

claim/schema.py

https://openimis.atlassian.net/browse/OTC-898
This PR adds None check in if statement to prevent from passing a None value to function.

OTC-898: update if conditions to match all the cases

---

.github/workflows/openmis-module-test.yml
claim/validations.py

https://openimis.atlassian.net/browse/793
The problem occurred when you were trying to valuate a claim with product created the same day. I added greater and equal to the date check and refactored a code a bit.

OTC-793: fix valuating a claim with item/service quantity exceeding the limit

---

locale/en/LC_MESSAGES/django.po

https://openimis.atlassian.net/browse/OTC-816
This PR updates django.po using gettext.sh

OTC-816: update django.po

---

locale/en/LC_MESSAGES/django.po

https://openimis.atlassian.net/browse/OTC-964
This PR is also a part of: https://github.com/openimis/openimis-be_py/pull/126

OTC-964: update translations

---

claim/views.py

Ticket: https://openimis.atlassian.net/browse/OTC-948
Changes:
- Converting claim to pdf now fixed.

OTC-948: Convertion to pdf fixed.

---

claim/models.py

https://openimis.atlassian.net/browse/OTC-1013
It is also a part of: 
https://github.com/openimis/openimis-be_py/pull/131
https://github.com/openimis/openimis-be-core_py/pull/161

OTC-1013: switch to username length limit from CoreConfig

---

claim/schema.py

https://openimis.atlassian.net/browse/OTC-1008
This PR adds filtering options according to location.
It is a part of: https://github.com/openimis/openimis-fe-claim_js/pull/83

OTC-1008: display claim admins with only valid health facilities

---

claim/gql_mutations.py

https://openimis.atlassian.net/browse/OTC-994
Changes:
- Fixed editing of a claim

OTC-994: Claim editing fix.

---

claim/gql_queries.py

https://openimis.atlassian.net/browse/OP-1324
It is related to this PR: https://github.com/openimis/openimis-fe-claim_js/pull/87

OP-1324: add gt filtering option to status in ClaimGQLType

---

claim/validations.py

https://openimis.atlassian.net/browse/OP-1354
This PR adds an if statement that recognizes if a claim is a hospitalization type.

OP-1354: add recognition of hospitalization calculation

---

claim/gql_queries.py

Include generateclaims and generateclaimadmins into the packaged version when installing from pypi or github branch spec.
Also tiny fix in attachment count with deleted attachments

OMT-324 generate commands in pkg

---

claim/validations.py

https://openimis.atlassian.net/browse/OTC-1063
This PR will allow to process claims without taking into account currently processed claim.

OP-1063: processing of claims

---

claim/validations.py

https://openimis.atlassian.net/browse/OP-1347
This PR will not reject a claim that has still some room for a item/service qty. It will reject iitem/service if policy is maxed out.

OP-1347: item/service claim subbmition limit fix

---

claim/validations.py

https://openimis.atlassian.net/browse/OP-1336
This PR fixes wrong calculation when claim exceeds ceiling on policy

OP-1336: fix calculation when exceeding ceiling

---

claim/schema.py

[Ticket here](https://openimis.atlassian.net/jira/software/c/projects/OP/issues/OP-1480)

OP-1480 - Fixed claim admin search

---

claim/schema.py

Ticket: https://openimis.atlassian.net/browse/ONI-61
FE PR: https://github.com/openimis/openimis-fe-claim_js/pull/117
Changes:
- Added option to filter claims by attachment status

ONI-61: Added claim status filter code.

---

claim/gql_mutations.py

Ticket: https://openimis.atlassian.net/browse/ONI-141
Changes:
- Fixed claim code length validation. Instead of hard coded value, existing setting is fetched.

ONI-141: Fixed claim code length validation.

---

claim/schema.py

https://openimis.atlassian.net/browse/OP-1533
This PR adds filter option to get only claims that have been restored.

OP-1533: allow to filter by restored claims

---

claim/gql_mutations.py

https://openimis.atlassian.net/browse/OP-1328
This PR generates submission clasim stats and puts them in the json_ext of MutationLog.
It needs: https://github.com/openimis/openimis-be-core_py/pull/212

OP-1328: generate claim submission stats

---

claim/schema.py

Ticket: https://openimis.atlassian.net/browse/ONI-84
Changes:
- Added query to fetch claims with the same diagnosis (for given insuree)

ONI-84: Claim with the same diagnosis query added.

---

claim/gql_mutations.py

https://openimis.atlassian.net/browse/ONI-180
Changes:
- Missing imports added

ONI-180: Add missing LocationManager import.

---

claim/migrations/0013_feedbackprompt.py
claim/migrations/0022_alter_feedbackprompt_phone_number.py
claim/models.py

https://openimis.atlassian.net/browse/OP-1812

OP-1812: FeedbackPrompt: Phone number field crashes while migrating

---

claim/models.py

[https://openimis.atlassian.net/browse/OM-130](https://openimis.atlassian.net/browse/OM-130)

OM-130 Fixed wrong config usage

---

claim/test_services.py
claim/tests.py

MERGING develop into release/24.04

MERGING develop into release/24.04

---

claim/reports/claims_primary_operational_indicators.py

Ticket: https://openimis.atlassian.net/browse/OP-1971
Changes:
- Removed redundant character from the report template
- It was breaking report code

OP-1791: Fixed primary operational indicators report template.

---

claim/reports/claims_overview.py

Ticket: https://openimis.atlassian.net/browse/OP-1967
Changes:
- Added missing import

OP-1967: Added missing import
